language: csharp
sudo: required
mono: none
dotnet: 3.0
os:
- linux
before_script:
- nuget install Codecov -Version 1.13.0 -OutputDirectory .\
- dotnet restore ".\CPS847Ass2\CPS847Ass2.sln"
script:
- dotnet build ".\CPS847Ass2\CPS847Ass2.sln" -c Release
- dotnet test ".\CPS847Ass2\CPS847Ass2.sln" -c Release -v n -l "trx;LogFileName=.\MyProject_coverage.xml"
- codecov -f .\MyProject_coverage.xml